### ISSUE TITLE
Unable to turn off natural mode / Timer not showing correct time

### ISSUE THREAD

**Issue by Piramidowy** [ikaruswill/lovelace-fan-xiaomi#53]
For dmaker.fan.p15 I'm unable to turn on/off nature mode. Even if Fan is in mode: nature, leaf icon stays black. After trigger it turns green for couple of seconds and goes black again without changing mode at all. 
As for timer, it shows 1h, then 1m and stays like that. 

My config is: 
```
type: 'custom:fan-xiaomi'
entity: fan.xiaomi_smart_fan_pro
disable_animation: false
name: Wentylator
platform: xiaomi_miio_fan
```

**Comment by insajd** [comment]
This should be fixed in latest version 1.5.4

**Comment by Piramidowy** [comment]
Unfortunately problem still persists.

![image](https://user-images.githubusercontent.com/4437845/117652954-1c1ef880-b194-11eb-9e68-cf5f4d23aa4e.png)

![image](https://user-images.githubusercontent.com/4437845/117652995-2b9e4180-b194-11eb-8f98-86561f4abbf0.png)

**Comment by Piramidowy** [comment]
@insajd You were right, after clearing cache, timer and natural mode switch are working fine.
One more thing that is not working are arrows (left / right) to rotate fan. There is no effect.

**Comment by insajd** [comment]
@Piramidowy please check http://homeassistant.local:8123/developer-tools/service whether there service fan.set_direction is working. Choose your fan, and click forward/backward. I don't see any reason arrows wouldn't be working for you with this card, unless service isn't working. 

If the service isn't working - create a ticket in this repo https://github.com/rytilahti/python-miio/ (file https://github.com/rytilahti/python-miio/blob/master/miio/fan_miot.py is what is used for your fan, my p5 fan is using another file).
If service is working - create a new ticket here.

Closing this particular ticket.
